from python_helper import DateTimeHelper


FIRST_MONTH_DAY = 1
DEFAULT_DUE_TIME = DateTimeHelper.DEFAULT_TIME_END
DEFAULT_CLOSING_TIME = DateTimeHelper.DEFAULT_TIME_END

CLOSING_DAY_REFERENCE = 'CLOSING_DAY_REFERENCE'
DUE_DAY_REFERENCE = 'DUE_DAY_REFERENCE'